version: "3.1"
services:

    redis:
        image: redis:alpine
        container_name: ${PROJECT_NAME}-redis

    postgres:
        image: postgres:14-alpine
        container_name: ${DB_HOST}
        volumes:
            - "./sourcefiles/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - "5432:5432"
        networks:
            - testing_net

    api:
        image: webdevops/php-apache-dev:8.1
        user: "1000:1000"
        container_name: ${PROJECT_NAME}-api
        working_dir: /app
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
        ports:
            - "8090:80"
        volumes:
            - ./:/app:rw
        networks:
            - testing_net


networks:
    testing_net:
